# Task 1:
Creat a 4 * 4 array containing values from 1 to 16 .

In [8]:
import numpy as np
values = np.arange(1 , 17).reshape(4, 4)
print(f"Shape of values: {values.shape}")
print(f"Data type of values: {values.dtype}")

Shape of values: (4, 4)
Data type of values: int64


# Task 2:
Extract the second column and the last row .

In [7]:
import numpy as np
values = np.arange(1 , 17).reshape(4, 4)
print(f"Values in the second column: {values[:,1]}")
print(f"Values in the last row: {values[-1,:]}")

Values in the second column: [ 2  6 10 14]
Values in the last row: [13 14 15 16]


# Task 3:
Select values greater than the matrix mean by using boolean masking .

In [6]:
import numpy as np
values = np.arange(1 , 17).reshape(4, 4)
print(f"Values greater than the mean: {values[values > values.mean()]}")

Values greater than the mean: [ 9 10 11 12 13 14 15 16]


# Task 4:
ADD 1D array to every row using broadcasting .

In [11]:
import numpy as np
values = np.arange(1 , 17).reshape(4, 4)
numbers = np.array([90, 21, 31, 10])
new_values = values + numbers
print(f"New values after addition: \n{new_values}")

# for cheking the results if it is correct or not

for i in range(4):
    for j in range(4):
        print(f"the value of this cell must be {numbers[j] + values[i][j]} and the value of this cell is {new_values[i][j]}")

New values after addition: 
[[ 91  23  34  14]
 [ 95  27  38  18]
 [ 99  31  42  22]
 [103  35  46  26]]
the value of this cell must be 91 and the value of this cell is 91
the value of this cell must be 23 and the value of this cell is 23
the value of this cell must be 34 and the value of this cell is 34
the value of this cell must be 14 and the value of this cell is 14
the value of this cell must be 95 and the value of this cell is 95
the value of this cell must be 27 and the value of this cell is 27
the value of this cell must be 38 and the value of this cell is 38
the value of this cell must be 18 and the value of this cell is 18
the value of this cell must be 99 and the value of this cell is 99
the value of this cell must be 31 and the value of this cell is 31
the value of this cell must be 42 and the value of this cell is 42
the value of this cell must be 22 and the value of this cell is 22
the value of this cell must be 103 and the value of this cell is 103
the value of this cell

# Final Mini Project

## Vehicle Sensor Analysis
This mini project analysez vehicle OBD-II sensor readings using NumPy

### Features
- Load sensor readings from a CSV file
- Compute statistical information
- Detect driving characteristics
- Generate a formatted analysis report
- Save the report automatically as a text file

## Why this project?
I intentionally selected automotive sensor data because it directly relates to my academic specialization in IOT&Embedded Systems and supports the direction of my graduation project.

Rather than treating the exercise as a standalone programming task, I wanted to practice newly learned cocepts in a context that reflects my long-term enginnering interests.

## Output

- console report
- 'vehicle_report.txt'


In [ ]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

sensors_data = np.genfromtxt('../../OBDii_data.csv', delimiter=',', skip_header=1)
sensors_data =np.delete(sensors_data, 0, axis=1)
print(sensors_data)
header = ["Engine_RPM", "Vehicle_Speed_KMH", "Throttle_Pos_Pct", "Coolant_Temp_C", "Engine_Load_Pct"]

max_speed = np.max(sensors_data[:,1])
mean_speed = np.mean(sensors_data[:,1])
min_speed = np.min(sensors_data[:,1])
speed_mps = sensors_data[: , 1] / 3.6

max_rpm = np.max(sensors_data[:,0])
min_rpm = np.min(sensors_data[:,0])
mean_rpm = np.mean(sensors_data[:,0])

max_coolant_temp = np.max(sensors_data[:,3])
min_coolant_temp = np.min(sensors_data[:,3])
mean_coolant_temp = np.mean(sensors_data[:,3])

max_load = np.max(sensors_data[:,4])
min_load = np.min(sensors_data[:,4])
mean_load = np.mean(sensors_data[:,4])


how_many_speed_over_mean = np.sum(sensors_data[:,1] > mean_speed)
how_many_rpm_over_2000 = np.sum(sensors_data[:,0] > 2000)
highest_speed_record = sensors_data[np.argmax(sensors_data[:,1])]

if mean_speed < 30:
    driving_condition = "City Driving"
elif mean_speed < 60:
    driving_condition = "Suburban Driving"
else:
    driving_condition = "Highway Driving"

report = f"""
============================================================================================
                                         Vehicle Sensor Data Report
============================================================================================
Driving Condition: {driving_condition}


Max Speed: {max_speed:.2f} km/h
Mean Speed: {mean_speed:.2f} km/h
Min Speed: {min_speed:.2f} km/h


Max RPM: {max_rpm:.2f}
Mean RPM: {mean_rpm:.2f}
Min RPM: {min_rpm:.2f}


Max Coolant Temp: {max_coolant_temp:.2f} °C
Mean Coolant Temp: {mean_coolant_temp:.2f} °C
Min Coolant Temp: {min_coolant_temp:.2f} °C


Max Engine Load: {max_load:.2f} %
Mean Engine Load: {mean_load:.2f} %
Min Engine Load: {min_load:.2f} %


Number of Speed Records Over Mean Speed: {how_many_speed_over_mean}

Number of RPM Records Over 2000: {how_many_rpm_over_2000}

Highest Speed Record: {header[1]}: {highest_speed_record[1]:.2f} km/h, {header[0]}: {highest_speed_record[0]:.2f} RPM, {header[2]}: {highest_speed_record[2]:.2f} %, {header[3]}: {highest_speed_record[3]:.2f} °C, {header[4]}: {highest_speed_record[4]:.2f} %    

speed in m/s: {speed_mps}

"""
print(report)
with open("vehicle_sensor_report.txt", "w") as report_file:
    report_file.write(report)


[[ 750.     0.    12.5   85.    18.4]
 [1200.     5.    18.    85.    25.1]
 [1800.    15.    22.4   85.    34.8]
 [2200.    28.    30.1   86.    45.2]
 [2400.    42.    35.5   86.    52. ]
 [2100.    50.    20.2   86.    28.7]
 [1600.    52.    14.8   87.    19.5]
 [1550.    55.    15.    87.    20.1]
 [1900.    63.    25.3   87.    38.6]
 [2300.    72.    32.    88.    48.9]
 [2150.    75.    18.5   88.    22.3]]

                                         Vehicle Sensor Data Report
Driving Condition: Suburban Driving


Max Speed: 75.00 km/h
Mean Speed: 41.55 km/h
Min Speed: 0.00 km/h


Max RPM: 2400.00
Mean RPM: 1813.64
Min RPM: 750.00


Max Coolant Temp: 88.00 °C
Mean Coolant Temp: 86.36 °C
Min Coolant Temp: 85.00 °C


Max Engine Load: 52.00 %
Mean Engine Load: 32.15 %
Min Engine Load: 18.40 %


Number of Speed Records Over Mean Speed: 7

Number of RPM Records Over 2000: 5

Highest Speed Record: Vehicle_Speed_KMH: 75.00 km/h, Engine_RPM: 2150.00 RPM, Throttle_Pos_Pct: 18.50 %, Coolan